### DISCUSSION TITLE
Generating clients with Encore in a GitHub action

### DISCUSSION THREAD

**Discussion by echarrod** [encoredev/encore#1409] [General]
Hello, I am trying to avoid the manual process of regenerating clients every time a commit is pushed to my main branch.

 I have tried adding a GitHub action:
 ```yaml
name: Generate Encore Clients

on:
  push:
    paths:
      - 'src/myProject/**/*.go'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git Config Globally
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          repository: myOrg/sourceRepo
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Install Encore CLI and Generate Clients
        run: |
          # Install Encore CLI
          curl -L https://encore.dev/install.sh | bash
          
          # Add Encore CLI to PATH for this shell session
          export ENCORE_INSTALL="$HOME/.encore"
          export PATH="$ENCORE_INSTALL/bin:$PATH"
          
          # Verify installation
          encore version
          
          # Generate the clients
          cd src/myProject
          encore gen client --env=local --output=gen/ts/client.ts
          encore gen client --env=local --lang=openapi --output=gen/ios/openapi.json

      - name: Checkout TS Client Repository
        uses: actions/checkout@v3
        with:
          repository: myOrg/ts-client
          path: ts-client
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Commit TypeScript Client
        run: |
          cd ts-client
          cp ../gen/ts/client.ts gen/encore/client.ts
          git add .
          git commit -m "gen: Update TypeScript client"
          git push

      - name: Checkout iOS Repository
        uses: actions/checkout@v3
        with:
          repository: myOrg/ios
          path: ios
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Commit OpenAPI Client
        run: |
          cd ios
          cp ../gen/ios/openapi.json app/Source/Core/ClientGen/openapi.json
          git add .
          git commit -m "gen: Update OpenAPI client"
          git push
```

It's the "Generating Clients" step I'm struggling with.
The above run gets the following error:
```shell
| error: the app <myAppName> must be run locally before generating a client for the 'local' environment.
```

I've then tried adding a `encore run` step, which seems to never complete, and also:
```yaml
encore run &
sleep 20s
encore gen client --env=local --output=gen/ts/client.ts
encore gen client --env=local --lang=openapi --output=gen/ios/openapi.json
```
to try to start it in a detached state, then attempt to wait for it to complete before generating the client.

I'm guessing there isn't currently a command in Encore that will allow the generating of a client, without the full running of the app with `encore run`?
