### DISCUSSION TITLE
GitHub action to regenerate TS, OpenAPI & Swift clients in separate repos

### DISCUSSION THREAD

**Discussion by echarrod** [encoredev/encore#1549] [Show and tell]
Adding a GitHub action which looks for Go changes and automatically regenerates means:
- you don't have to worry about generating the clients yourself
- you're less likely to have the BE/FE out of sync.

Add to .github/workflows in the source repo where your encore code is:
```yaml
name: Generate Encore Clients

on:
  push:
    paths:
      - 'src/**/*.go'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          repository: my-org-name/backend
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Install Encore CLI + Generate Clients
        run: |
          # Install Encore CLI
          curl -L https://encore.dev/install.sh | bash

          # Add Encore CLI to PATH for this shell session
          export ENCORE_INSTALL="$HOME/.encore"
          export PATH="$ENCORE_INSTALL/bin:$PATH"

          # Verify installation
          encore version

          # Generate the clients
          cd src
          encore check
          encore gen client --env=local --output=client.ts
          encore gen client --env=local --lang=openapi --output=openapi.json

      - name: Upload Client Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: clients
          path: |
            src/client.ts
            src/openapi.json

  update-my-ts-repo:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Set Git Config Globally
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Checkout Admin Console Repository
        uses: actions/checkout@v3
        with:
          repository: my-org-name/my-ts-repo
          path: my-ts-repo
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Download Client Artifacts
        uses: actions/download-artifact@v3
        with:
          name: clients

      - name: Commit TypeScript Client
        run: |
          cd my-ts-repo
          ls ../
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "gen: Update OpenAPI client"
            git push
          fi

  update-ios:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Set Git Config Globally
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Checkout iOS Repository
        uses: actions/checkout@v3
        with:
          repository: my-org-name/ios
          path: ios
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Download Client Artifacts
        uses: actions/download-artifact@v3
        with:
          name: clients

      - name: Commit OpenAPI Client
        run: |
          cd ios
          cp ../openapi.json app/Source/Core/ClientGen/openapi.json
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            npm install @openapitools/openapi-generator-cli -g
            export PATH="$(npm config get prefix)/bin:$PATH"
            openapi-generator-cli generate -i app/Source/Core/ClientGen/openapi.json -g swift5 -o ./app/Source/Core/ClientGen
            git add .
            git commit -m "gen: Update OpenAPI client"
            git push
          fi
```
