### DISCUSSION TITLE
.pre-commit-config.yaml for running encore tests

### DISCUSSION THREAD

**Discussion by echarrod** [encoredev/encore#1555] [Show and tell]
I frequently found my deploys were broken because of a failing test, which I didn't realise for a little while. 

Adding to pre-commit allows you to "shift left" the failures, so they are caught earlier, at commit time.

This is for use with https://pre-commit.com/, but I'm interested to hear how others have solved this.

Using the custom `my-cmd-mod` command provided on https://github.com/TekWizely/pre-commit-golang:
```yaml
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: my-cmd-mod
        name: encore-test
        alias: encore-test
        args: [ encore, test, ./... ]
```

This does run all of the tests. Ideally we'd only run the tests for the changed packages, but I couldn't get it to work like that, as I'm not sure if we could "skip" the non-encore packages (if there are any).

This is similar to how the "[go test](https://github.com/TekWizely/pre-commit-golang?tab=readme-ov-file#go-test)" hook works, and `-mod` above can be substituted for the other prefixed below:
### go-test
Automates testing, printing a summary of test results.

| Hook ID            | Description
|--------------------|------------
| `go-test-mod`      | Run `'cd $(mod_root $FILE); go test [$ARGS] ./...'` for each staged .go file
| `go-test-pkg`      | Run `'go test [$ARGS] ./$(dirname $FILE)'` for each staged .go file
| `go-test-repo-mod` | Run `'cd $(mod_root); go test [$ARGS] ./...'` for each module in the repo
| `go-test-repo-pkg` | Run `'go test [$ARGS] ./...'` in repo root folder
