### ISSUE TITLE
How to register pgxgeos on database connection? Issues inserting go-geos Geometry's

### ISSUE THREAD

**Issue by jdaily** [encoredev/encore#1455]
I'm using the go-geos geos package for sqlc 

```
sql_package: "pgx/v5"
        overrides:
          - db_type: "geometry"
            go_type:
              import: "github.com/twpayne/go-geos"
              package: "geos"
              pointer: true
              type: "Geom"
            nullable: true
          - db_type: "geometry"
            go_type:
              import: "github.com/twpayne/go-geos"
              package: "geos"
              type: "Geom"
```
and it appears to compile my queries as expected from my schema's

```
location geometry(Point, 4326) NOT NULL,
```

However I'm  getting this error on Insert ```failed to encode args[7]: unable to encode geos.Geom{context:(*geos.Context)(0x140001be000), geom:(*geos._Ctype_struct_GEOSGeom_t)(0x6000033dc000), parent:(*geos.Geom)(nil), typeID:0, numGeometries:1, numInteriorRings:0, numPoints:0} into text format for unknown type (OID 28177): cannot find encode plan```

I've assumed it's because I've not yet figured out how to [configure the connection pool to use go-geos](https://docs.sqlc.dev/en/latest/reference/datatypes.html#using-github-com-twpayne-go-geos-pgx-v5-only). 
I don't see any functions in `encore.dev/storage/sqldb` that would enable me to call AfterConnect. Can you provide some guidance?
